import type { Empresa } from "@/interfaces/empresa.interface"
import type { Producto, GrupoProducto } from "@/interfaces/productos.interface"
import type { Mesa, AreaVenta, PlanodeMesas } from "@/interfaces/mesas.interface"
import type { Cliente } from "@/interfaces/clientes.interface"
import { generateULID } from "./ulid"

// Mock data para empresas
export const mockEmpresas: Empresa[] = [
  {
    EmpresaULID: generateULID(),
    RazonSocial: "Restaurante El Buen Sabor S.A. de C.V.",
    NombreComercial: "El Buen Sabor",
    RFC: "RBS123456789",
    Direccion: "Av. Principal 123, Col. Centro",
    Telefono: "5551234567",
    Email: "contacto@elbuensabor.com",
    SitioWeb: "https://elbuensabor.com",
    TipoEmpresa: "Restaurante",
    Activa: true,
    FechaRegistro: new Date("2024-01-01"),
    Fecha_UltimoCambio: new Date(),
    UsuarioULID: generateULID(),
  },
]

// Mock data para grupos de productos
export const mockGruposProductos: GrupoProducto[] = [
  {
    GrupoProductoULID: generateULID(),
    ClaveGrupo: "ENT",
    Orden: 1,
    Descripcion: "Entradas",
    Clasificacion: "Aperitivos",
    MenuQR: true,
    CatalogoOnline: true,
    APPComensal: true,
    Inactiva: false,
    Paletacolor: "#FF6B35",
    Sucursales: true,
    AplicarComentarios: true,
    Fecha_UltimoCambio: new Date(),
    UsuarioULID: generateULID(),
  },
  {
    GrupoProductoULID: generateULID(),
    ClaveGrupo: "PLAT",
    Orden: 2,
    Descripcion: "Platillos Principales",
    Clasificacion: "Principales",
    MenuQR: true,
    CatalogoOnline: true,
    APPComensal: true,
    Inactiva: false,
    Paletacolor: "#D97706",
    Sucursales: true,
    AplicarComentarios: true,
    Fecha_UltimoCambio: new Date(),
    UsuarioULID: generateULID(),
  },
  {
    GrupoProductoULID: generateULID(),
    ClaveGrupo: "BEB",
    Orden: 3,
    Descripcion: "Bebidas",
    Clasificacion: "Bebidas",
    MenuQR: true,
    CatalogoOnline: true,
    APPComensal: true,
    Inactiva: false,
    Paletacolor: "#059669",
    Sucursales: true,
    AplicarComentarios: false,
    Fecha_UltimoCambio: new Date(),
    UsuarioULID: generateULID(),
  },
]

// Mock data para productos
export const mockProductos: Producto[] = [
  {
    ProductoULID: generateULID(),
    GrupoProductoULID: mockGruposProductos[0].GrupoProductoULID,
    ClaveProducto: "ENT001",
    TipoProducto: "Platillo",
    Nombredelproducto: "Nachos Supremos",
    Favorito: true,
    Descripcion: "Nachos con queso, jalapeños, guacamole y crema",
    ExentoImpuesto: false,
    PrecioAbierto: false,
    UnidadesULID: generateULID(),
    AreaProduccionULID: generateULID(),
    AlmacenULID: generateULID(),
    ControlStock: false,
    PrecioxUtilidadad: true,
    Facturable: true,
    Suspendido: false,
    Comedor: true,
    ADomicilio: true,
    Mostrador: true,
    Enlinea: true,
    EnAPP: true,
    CanalesVenta: true,
    EnMenuQR: true,
    Fecha_UltimoCambio: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
  {
    ProductoULID: generateULID(),
    GrupoProductoULID: mockGruposProductos[1].GrupoProductoULID,
    ClaveProducto: "PLAT001",
    TipoProducto: "Platillo",
    Nombredelproducto: "Tacos al Pastor",
    Favorito: true,
    Descripcion: "Tacos de trompo con piña, cebolla y cilantro",
    ExentoImpuesto: false,
    PrecioAbierto: false,
    UnidadesULID: generateULID(),
    AreaProduccionULID: generateULID(),
    AlmacenULID: generateULID(),
    ControlStock: false,
    PrecioxUtilidadad: true,
    Facturable: true,
    Suspendido: false,
    Comedor: true,
    ADomicilio: true,
    Mostrador: true,
    Enlinea: true,
    EnAPP: true,
    CanalesVenta: true,
    EnMenuQR: true,
    Fecha_UltimoCambio: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
]

// Mock data para planos de mesas
export const mockPlanosMesas: PlanodeMesas[] = [
  {
    PlanoULID: generateULID(),
    NombrePlanodeMesas: "Planta Baja",
    ComensalesMaximos: 120,
    Activo: true,
    Fecha_UltimoCambio: new Date(),
    Fecha_Sync: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
]

// Mock data para áreas de venta
export const mockAreasVenta: AreaVenta[] = [
  {
    AreaULID: generateULID(),
    PlanoULID: mockPlanosMesas[0].PlanoULID,
    Descripcion: "Terraza",
    Fumar: true,
    Exterior: true,
    Barra: false,
    Fecha_UltimoCambio: new Date(),
    Fecha_Sync: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
  {
    AreaULID: generateULID(),
    PlanoULID: mockPlanosMesas[0].PlanoULID,
    Descripcion: "Salón Principal",
    Fumar: false,
    Exterior: false,
    Barra: false,
    Fecha_UltimoCambio: new Date(),
    Fecha_Sync: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
  {
    AreaULID: generateULID(),
    PlanoULID: mockPlanosMesas[0].PlanoULID,
    Descripcion: "Barra",
    Fumar: false,
    Exterior: false,
    Barra: true,
    Fecha_UltimoCambio: new Date(),
    Fecha_Sync: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
]

// Mock data para mesas
export const mockMesas: Mesa[] = [
  {
    MesaULID: generateULID(),
    ClaveMesa: "01",
    NombreMesa: "Mesa 1",
    TipoMesaULID: generateULID(),
    AreaVentasULID: mockAreasVenta[1].AreaULID,
    ComensalesMaximos: 4,
    Estado: "Disponible",
    Fecha_UltimoCambio: new Date(),
    Fecha_Sync: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
  {
    MesaULID: generateULID(),
    ClaveMesa: "02",
    NombreMesa: "Mesa 2",
    TipoMesaULID: generateULID(),
    AreaVentasULID: mockAreasVenta[1].AreaULID,
    ComensalesMaximos: 6,
    Estado: "Ocupada",
    Fecha_UltimoCambio: new Date(),
    Fecha_Sync: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
  {
    MesaULID: generateULID(),
    ClaveMesa: "03",
    NombreMesa: "Mesa 3",
    TipoMesaULID: generateULID(),
    AreaVentasULID: mockAreasVenta[0].AreaULID,
    ComensalesMaximos: 2,
    Estado: "Reservada",
    Fecha_UltimoCambio: new Date(),
    Fecha_Sync: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
  {
    MesaULID: generateULID(),
    ClaveMesa: "04",
    NombreMesa: "Mesa 4",
    TipoMesaULID: generateULID(),
    AreaVentasULID: mockAreasVenta[1].AreaULID,
    ComensalesMaximos: 8,
    Estado: "Limpieza",
    Fecha_UltimoCambio: new Date(),
    Fecha_Sync: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
]

// Mock data para clientes
export const mockClientes: Cliente[] = [
  {
    ClienteULID: generateULID(),
    ClaveCliente: "CLI001",
    NombreCompleto: "Juan Pérez García",
    Telefono: "5551234567",
    Email: "juan.perez@email.com",
    FechaNacimiento: new Date("1985-05-15"),
    Direccion: "Calle Falsa 123",
    CodigoPostal: "12345",
    Ciudad: "Ciudad de México",
    Estado: "CDMX",
    Pais: "México",
    TipoCliente: "Frecuente",
    Activo: true,
    Puntos: 150,
    FechaRegistro: new Date("2024-01-15"),
    Fecha_UltimoCambio: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
  {
    ClienteULID: generateULID(),
    ClaveCliente: "CLI002",
    NombreCompleto: "María González López",
    Telefono: "5559876543",
    Email: "maria.gonzalez@email.com",
    TipoCliente: "VIP",
    Activo: true,
    Puntos: 500,
    FechaRegistro: new Date("2023-12-01"),
    Fecha_UltimoCambio: new Date(),
    UsuarioULID: generateULID(),
    EmpresaULID: mockEmpresas[0].EmpresaULID,
  },
]

// Estadísticas mock
export const mockEstadisticas = {
  ventasHoy: 15420.5,
  ventasAyer: 12350.75,
  mesasOcupadas: 8,
  mesasDisponibles: 12,
  clientesAtendidos: 45,
  productosVendidos: 127,
  promedioTicket: 342.68,
  tiempoPromedioAtencion: 25, // minutos
}
